> <strong>本专栏将从基础开始，循序渐进，由浅入深讲解Java的基本使用，希望大家都能够从中有所收获，也请大家多多支持。</strong>
> <strong>专栏地址:[26天高效学习Java编程](https://blog.csdn.net/learning_xzj/category_11806176.html) </strong>
> <strong>相关软件地址:[软件地址](https://pan.baidu.com/s/1bXCZR0yxN2-v6NqDpe4H1g?pwd=1111) </strong>
> <strong>所有代码地址:[代码地址](https://gitee.com/codinginn/java-code) </strong>
> <strong> 如果文章知识点有错误的地方，请指正！大家一起学习，一起进步。</strong>
> <font color="red"><strong> 如果感觉博主的文章还不错的话，还请关注、点赞、收藏三连支持一下博主哦</strong></font>

@[toc]



**本文将讲解异常的产生和处理，以及如何自定义异常**



# 第四章   异常

## 知识点-- 异常

### 目标

- 能够辨别程序中异常和错误的区别,并且说出异常的分类

### 讲解

#### 异常概念

**异常** 指的是程序在执行过程中，出现的非正常的情况，最终会导致JVM的非正常停止。

**注意:** 在Java等面向对象的编程语言中，**异常本身是一个类，产生异常就是创建异常对象并抛出了一个异常对象**。Java处理异常的方式是中断处理。

#### 异常体系

异常机制其实是帮助我们**找到**程序中的问题，异常的根类是`java.lang.Throwable`，其下有两个子类：`java.lang.Error`与`java.lang.Exception`，平常所说的异常指`java.lang.Exception`。

![](imgs.assets/异常体系.png)

**Throwable体系：**

- **Error**:严重错误Error，无法通过处理的错误，只能事先避免。
- **Exception**:表示异常，异常产生后程序员可以通过代码的方式纠正，使程序继续运行，是必须要处理的。

#### 异常分类

我们平常说的异常就是指Exception，因为这类异常一旦出现，我们就要对代码进行更正，修复程序。

**异常(Exception)的分类**:根据在编译时期还是运行时期去检查异常?

- **编译时期异常**:checked异常。在编译时期,就会检查,如果没有处理异常,则编译失败。(如日期格式化异常)
- **运行时期异常**:runtime异常。在运行时期,检查异常.在编译时期,运行异常不会编译器检测(不报错)。(如数学异常)

​    ![](imgs.assets/异常的分类.png)

#### 异常的产生过程解析

先运行下面的程序，程序会产生一个数组索引越界异常ArrayIndexOfBoundsException。我们通过图解来解析下异常产生的过程。

 工具类

```java
public class ArrayTools {
    // 对给定的数组通过给定的角标获取元素。
    public static int getElement(int[] arr, int index) {
        int element = arr[index];
        return element;
    }
}
```

 测试类

```java
public class ExceptionDemo {
    public static void main(String[] args) {
        int[] arr = { 34, 12, 67 };
        intnum = ArrayTools.getElement(arr, 4)
        System.out.println("num=" + num);
        System.out.println("over");
    }
}
```

上述程序执行过程图解：

 ![](imgs.assets/异常产生过程.png)

# 第五章 异常的产生和处理

## 知识点-- 异常的产生

### 目标

- 能够理解使用throw关键字产生异常

### 讲解

#### throw关键字的作用

在java中，提供了一个**throw**关键字，它用来抛出一个指定的异常对象。throw**用在方法内**，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。

#### throw关键字的使用格式

```
throw new 异常类名(参数);
```

 例如：

```java
throw new NullPointerException("要访问的arr数组不存在");
throw new ArrayIndexOutOfBoundsException("该索引在数组中不存在，已超出范围");
```

#### 案例演示

```java

public class Test {
    public static void main(String[] args) {
        /*
            throw关键字:
                作用:throw用在方法内，用来抛出一个异常对象，将这个异常对象传递到调用者处，并结束当前方法的执行。
                格式: throw 异常对象;
         */
        int[] arr = {10,20,30,40};
        method(arr,4);
    }

    /**
     * 查找指定索引位置的元素
     * @param arr
     * @param index
     */
    public static void method(int[] arr,int index){
        if (index < 0 || index > arr.length-1){
            // 索引不存在-->产生一个异常
            throw new ArrayIndexOutOfBoundsException(index+"");
        }else{
            int num = arr[index];
            System.out.println(num);
        }
    }
}

```

## 知识点--声明处理异常

### 目标

- 掌握声明处理异常

### 讲解

#### 声明处理异常的概述

**声明处理异常**：使用throws关键字将问题标识出来, 表示当前方法不处理异常，而是提醒给调用者, 让调用者来处理....最终会到虚拟机,虚拟机直接结束程序,打印异常信息。

#### 声明处理异常格式

```java
修饰符 返回值类型 方法名(参数) throws 异常类名1,异常类名2…{  // 可以抛出一个,也可以多个
}	
```

#### 案例演示

```java


import java.io.FileNotFoundException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;


public class Test {
    // 使用throws关键字将异常标识出来, 表示当前方法不处理异常，而是提醒调用者来处理
    public static void main(String[] args) throws ParseException {
        /*
            处理异常的目的: 为了让程序可以继续往下执行
            声明处理异常:
                概述:使用throws关键字将问题标识出来, 表示当前方法不处理异常，而是提醒给调用者,
                    让调用者来处理....最终会到虚拟机,虚拟机直接结束程序,打印异常信息。

                格式:
                    修饰符 返回值类型 方法名(形参列表) throws 异常类名1,异常类名2…{  // 可以抛出一个,也可以多个

                    }
                特点: 声明处理异常,处理完后,如果程序运行的时候出现异常,程序还是无法继续往下执行
                使用场景:  声明处理异常一般处理运行的时候不会出现异常的编译异常

         */
        //method1();

        // 举例:声明处理异常一般处理运行的时候不会出现异常的编译异常
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse("1999-10-10");
        System.out.println(date);

        // 举例:一般用来处理编译异常,让程序通过编译,但程序运行的时候出现异常,程序还是无法继续往下执行
        /*SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date date = sdf.parse("1999年10月10日");
        System.out.println(date);*/

        System.out.println("结束");

    }


    // 一次声明处理一个异常
    // 使用throws关键字将异常标识出来, 表示当前方法不处理异常，而是提醒调用者来处理
    public static void method1() throws ParseException{
        // 产生一个异常对象
        throw new ParseException("解析异常",1);
    }

    // 一次声明处理多个异常
    public static void method2(int num) throws ParseException,FileNotFoundException{
        // 产生一个异常对象
        if (num == 1){
            throw new ParseException("解析异常",1);
        }else{
            throw new FileNotFoundException("文件找不到异常");
        }
    }

}

```

## 知识点--捕获处理异常try…catch

### 目标

- 掌握捕获处理异常

### 讲解

#### 捕获处理异常的概述

- **捕获处理异常**：对异常进行捕获处理 , 处理完后程序可以正常向下执行。

#### 捕获处理异常格式

```java
try{
     编写可能会出现异常的代码
}catch(异常类型  e){
     处理异常的代码
     //记录日志/打印异常信息
}
执行步骤:
	1.首先执行try中的代码,如果try中的代码出现了异常,那么就直接执行catch()里面的代码,执行完后,程序继续往下执行
    2.如果try中的代码没有出现异常,那么就不会执行catch()里面的代码,而是继续往下执行
```

> 注意:
>
> 1. try和catch都不能单独使用,必须连用。
> 2. try中的代码出现了异常,那么出现异常位置后面的代码就不会再执行了
> 3. 捕获处理异常,如果程序出现了异常,程序会继续往下执行
>
> ​       声明处理异常,如果程序出现了异常,程序就不会继续往下执行

演示如下：

```java
import java.text.ParseException;

public class Test {
    public static void main(String[] args) {
        /*
            捕获处理异常: try...catch..
                概述:对异常进行捕获处理 , 处理完后程序可以正常向下执行。
                格式:
                    try{
                         编写可能会出现异常的代码
                    }catch(异常类型  变量名){
                         处理异常的代码
                         //记录日志/打印异常信息
                    }
                执行步骤:
	                1.首先执行try中的代码,如果try中的代码出现了异常,那么就直接执行catch()里面的代码,执行完后,程序继续往下执行
                    2.如果try中的代码没有出现异常,那么就不会执行catch()里面的代码,而是继续往下执行
         */
        method1();
        System.out.println("======================");
        // 捕获处理运行异常
        try {
            System.out.println(1/1);// 没有出现异常,1
        }catch (ArithmeticException e){
            System.out.println("出现了数学运算异常");
        }
        System.out.println("======================");

        try {
            System.out.println(1/0);// 出现了异常
            System.out.println("try...");
        }catch (ArithmeticException e){
            System.out.println("出现了数学运算异常");
        }
        System.out.println("结束");
    }

    // 捕获处理编译异常
    public static void method1(){
        try{
            throw new ParseException("解析异常",1);
        }catch (ParseException e){
            System.out.println("出现了异常");
        }
        System.out.println("method1方法结束...");
    }
}

```

#### 获取异常信息

Throwable类中定义了一些查看方法:

- `public String getMessage()`:获取异常的描述信息,原因(提示给用户的时候,就提示错误原因。


- `public String toString()`:获取异常的类型和异常描述信息(不用)。
- `public void printStackTrace()`:打印异常的跟踪栈信息并输出到控制台。

​            *包含了异常的类型,异常的原因,还包括异常出现的位置,在开发和调试阶段,都得使用printStackTrace。*

在开发中呢也可以在catch将编译期异常转换成运行期异常处理。

```java

public class Test {
    public static void main(String[] args) {
        /*
            Throwable获取异常信息的方法:
            - public String getMessage():获取异常的描述信息,原因(提示给用户的时候,就提示错误原因。
            - public String toString():获取异常的类型和异常描述信息(不用)。
            - public void printStackTrace():打印异常的跟踪栈信息并输出到控制台。
         */
        System.out.println("开始");

        try {
            System.out.println(1/0);// 报异常,产生一个异常对象

        }catch (ArithmeticException e){
            /*System.out.println("出现了异常");
            System.out.println(e.getMessage());
            System.out.println(e);
            System.out.println(e.toString());*/
            e.printStackTrace();
            
        }

        System.out.println("结束");
    }
}

```



## 知识点--finally 代码块

### 目标

- 掌握finally代码块的格式和执行流程

### 路径

- finally代码块的概述
- finally代码块的语法格式
- 案例演示

### 讲解

#### finally代码块的概述

**finally**：有一些特定的代码无论异常是否发生，都需要执行。另外，因为异常会引发程序跳转，导致有些语句执行不到。而finally就是解决这个问题的，在finally代码块中存放的代码都是一定会被执行的。

#### finally代码块的语法格式

```java
try{
    可能会出现异常的代码
        
}catch(异常的类型 变量名){
    处理异常的代码或者打印异常的信息
}finally{
    无论异常是否发生,都会执行这里的代码(正常情况,都会执行finally中的代码,一般用来释放资源)
}

执行步骤:
 1.首先执行try中的代码,如果try中的代码出现了异常,那么就直接执行catch()里面的代码,执行完后会执行finally中的代码,然后程序继续往下执行
 2.如果try中的代码没有出现异常,那么就不会执行catch()里面的代码,但是还是会执行finally中的代码,然后程序继续往下执行
```

> 注意:finally不能单独使用。

#### 案例演示

```java

public class Test {
    public static void main(String[] args) {
        /*
            finally 代码块:
                概述:在finally代码块中存放的代码都是一定会被执行的
                格式:
                    try{
                        可能会出现异常的代码

                    }catch(异常的类型 变量名){
                        处理异常的代码或者打印异常的信息
                    }finally{
                        无论异常是否发生,都会执行这里的代码(正常情况,都会执行finally中的代码,一般用来释放资源)
                    }

                执行步骤:
                 1.首先执行try中的代码,如果try中的代码出现了异常,那么就直接执行catch()里面的代码,执行完后会执行finally中的代码,然后程序继续往下执行
                 2.如果try中的代码没有出现异常,那么就不会执行catch()里面的代码,但是还是会执行finally中的代码,然后程序继续往下执行
         */
        System.out.println("开始");
        /*try {
            System.out.println(1/0);
        }catch (ArithmeticException e){
            System.out.println("catch 出现了异常");
            return;
            //System.exit(0);
        }finally {
            System.out.println("finally 无论是否发生异常都会执行");
        }*/

        System.out.println("================================");
        try {
            System.out.println(1/1);// 1
            return;
        }catch (ArithmeticException e){
            System.out.println("catch 出现了异常");
        }finally {
            System.out.println("finally 无论是否发生异常都会执行");
        }
        System.out.println("结束");
    }
}

```

> 当只有在try或者catch中调用退出JVM的相关方法（如exist）,此时finally才不会执行,否则finally永远会执行。



## 扩展--finally经典面试题

```java

public class Test {
    public static void main(String[] args) {
        System.out.println(method1());// 30
        System.out.println(method2());// 20
    }

    public static int method1() {
        int num = 10;
        try {
            System.out.println(1 / 0);
        } catch (ArithmeticException e) {
            num = 20;
            return num;
        } finally {
            num = 30;
            return num;
        }
    }

    public static int method2() {
        int num = 10;
        try {
            System.out.println(1 / 0);
        } catch (ArithmeticException e) {
            num = 20;
            // catch中的return会做2件事:1.先记录要返回的值,然后执行finally中的代码,2.最后把记录的值返回
            return num;// 记录要返回的值:20
        } finally {
            num = 30;
        }
        return num;
    }
}

```



## 知识点--异常注意事项

### 目标

- 理解异常注意事项

### 讲解

- 运行时异常被抛出可以不处理。即不捕获也不声明抛出。

- 如果父类的方法抛出了多个异常,子类覆盖(重写)父类方法时,只能抛出相同的异常或者是他的子集。

- 父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出

- 声明处理多个异常,可以直接声明这多个异常的父类异常

- 在try/catch后可以追加finally代码块，其中的代码一定会被执行，通常用于资源回收。

- 多个异常使用捕获又该如何处理呢？

  1. 多个异常分别处理。
  2. 多个异常一次捕获，多次处理。
  3. 多个异常一次捕获一次处理。

- 当多异常分别处理时，捕获处理，前边的类不能是后边类的父类

  一般我们是使用一次捕获多次处理方式，格式如下：

  ```java
  try{
       编写可能会出现异常的代码
  }catch(异常类型A  e){  当try中出现A类型异常,就用该catch来捕获.
       处理异常的代码
       //记录日志/打印异常信息/继续抛出异常
  }catch(异常类型B  e){  当try中出现B类型异常,就用该catch来捕获.
       处理异常的代码
       //记录日志/打印异常信息/继续抛出异常
  }
  ```

  > 注意:这种异常处理方式，要求多个catch中的异常不能相同，并且若catch中的多个异常之间有子父类异常的关系，那么子类异常要求在上面的catch处理，父类异常在下面的catch处理。

代码如下:

```java


import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;

class Fu {
    public void show() throws ParseException, FileNotFoundException {
        // ...
    }

    public void run() {

    }
}

class Zi extends Fu {
    // 2.如果父类的方法抛出了多个异常,子类覆盖(重写)父类方法时,只能抛出相同的异常或者是他的子集。
   /* @Override
    public void show() throws ParseException, FileNotFoundException, IOException {

    }*/

   // 3.父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常,只能捕获处理
    @Override
    public void run() {
        try {
            throw new FileNotFoundException("");
        }catch (FileNotFoundException e){

        }
    }
}

public class Test {
    public static void main(String[] args) {
        /*
            异常注意事项:
                1.运行时异常被抛出可以不处理。即不捕获也不声明抛出。
                2.如果父类的方法抛出了多个异常,子类覆盖(重写)父类方法时,只能抛出相同的异常或者是他的子集。
                3.父类方法没有抛出异常，子类覆盖父类该方法时也不可抛出异常。此时子类产生该异常，只能捕获处理，不能声明抛出
                4.声明处理多个异常,可以直接声明这多个异常的父类异常
                5.在try/catch后可以追加finally代码块，其中的代码一定会被执行，通常用于资源回收。
                6.多个异常使用捕获又该如何处理呢？
                    1. 多个异常分别处理。
                    2. 多个异常一次捕获，多次处理。
                    3. 多个异常一次捕获一次处理。
                7.当多异常分别处理时，捕获处理，前边的类不能是后边类的父类
         */
    }

    // 1.运行时异常被抛出可以不处理。即不捕获也不声明抛出。
    public static void show1() {
        System.out.println(1 / 0);
    }

    // 4.声明处理多个异常,可以直接声明这多个异常的父类异常
    public static void show2(int num) throws Exception{
        if (num == 1){
            throw new FileNotFoundException("");
        }else{
            throw new ParseException("",1);
        }
    }

    // 多个异常使用捕获又该如何处理呢？
    // 1. 多个异常分别处理。
    public static void show3(int num) {
        if (num == 1){
            try {
                throw new FileNotFoundException("");
            } catch (FileNotFoundException e) {

            }
        }else{
            try {
                throw new ParseException("",1);
            } catch (ParseException e) {

            }
        }
    }
    // 2. 多个异常一次捕获，多次处理。
    public static void show4(int num) {
        try {
            if (num == 1){
                throw new FileNotFoundException("");
            }else{
                throw new ParseException("",1);
            }
        }catch (FileNotFoundException e){

        }catch (ParseException e){

        }
    }
    // 3. 多个异常一次捕获一次处理。
    public static void show5(int num) {
        try {
            if (num == 1){
                throw new FileNotFoundException("");
            }else{
                throw new ParseException("",1);
            }
        }catch (Exception e){

        }
    }
    // 7.当多异常分别处理时，捕获处理，前边的类不能是后边类的父类
    public static void show6(int num) {
        try {
            if (num == 1){
                throw new FileNotFoundException("");
            }else{
                throw new ParseException("",1);
            }
        }catch (Exception e){

        }/*catch (ParseException e){

        }*/
    }
}

```

# 第六章 自定义异常

## 知识点-- 自定义异常

### 目标

- 能够自定义并使用异常类

### 讲解

#### 自定义异常概述

**为什么需要自定义异常类:**

我们说了Java中不同的异常类,分别表示着某一种具体的异常情况,那么在开发中总是有些异常情况是预先没有定义好的,例如年龄负数问题,考试成绩负数问题.这些异常在JDK中没有定义过,此时我们根据自己业务的异常情况来定义异常类。

**什么是自定义异常类:**

在开发中根据自己业务的异常情况来定义异常类.

自定义一个业务逻辑异常: **RegisterException**。一个注册异常类。

**异常类如何定义:**

1. 自定义一个编译期异常: 自定义类 并继承于`java.lang.Exception`。
2. 自定义一个运行时期的异常类:自定义类 并继承于`java.lang.RuntimeException`。

```java

// 编译异常
public class MyException1 extends Exception {

    public MyException1() {
    }

    public MyException1(String message) {
        super(message);
    }
}



// 运行异常
public class MyException2 extends RuntimeException {
    public MyException2() {
    }

    public MyException2(String message) {
        super(message);
    }
}

public class Test {
    public static void main(String[] args)  {
        /*
            异常类如何定义:
                1. 自定义一个编译期异常: 自定义类 并继承于java.lang.Exception。
                2. 自定义一个运行时期的异常类:自定义类 并继承于java.lang.RuntimeException。

         */
        //throw new MyException1("自定义异常1");

        throw new MyException2("自定义异常2");
    }
}

```



#### 自定义异常的练习

要求：我们模拟注册操作，如果用户名已存在，则抛出异常并提示：亲，该用户名已经被注册。

首先定义一个注册异常类RegisterException：

```java
// 业务逻辑异常
public class RegisterException extends Exception {
    /**
     * 空参构造
     */
    public RegisterException() {
    }

    /**
     *
     * @param message 表示异常提示
     */
    public RegisterException(String message) {
        super(message);
    }
}
```

模拟登陆操作，使用数组模拟数据库中存储的数据，并提供当前注册账号是否存在方法用于判断。

```java


import java.util.Scanner;


public class Test {
    public static void main(String[] args) {
        // 需求:我们模拟注册操作，如果用户名已存在，则抛出异常并提示：亲，该用户名已经被注册。
        // 1.定义一个数组,存储一些已知用户名
        String[] names = {"jack", "rose", "jim", "tom"};

        // 2.用户输入要注册的用户名
        Scanner sc = new Scanner(System.in);
        System.out.println("请输入一个用户名:");
        String name = sc.next();

        // 3.循环遍历数组
        for (String s : names) {
            // 4.在循环中,判断用户输入的用户名和已知的用户名是否相同
            if (s.equals(name)) {
                // 5.如果相同,就抛出异常对象
                try {
                    throw new RegisterException("亲，该用户名已经被注册。");
                } catch (RegisterException e) {
                    System.out.println(e.getMessage());
                    return;
                }
            }
        }

        // 6.如果不相同,就显示提示信息
        System.out.println("亲,恭喜您注册成功!");
    }
}

```





